### ISSUE TITLE
Fix error when inserting into time series collections

### ISSUE THREAD

**Issue by pavlos163** [typegoose/mongodb-memory-server#903]
## Versions

- NodeJS: 20.11.1
- mongodb-memory-server-*: 10.1.2
- mongodb(the binary version): 8.0.3
- mongoose: 8.8.2
- system: Linux Debian (from node:20.11.1-slim Docker image)

package: mongo-memory-server 

## What is the Problem?
When using mongodb-memory-server with a timeseries collection in test environment, attempting to insert documents results in `MongoServerError: Namespace X is a view, not a collection`. The same code works correctly with a local MongoDB instance.

This appears to be a discrepancy in how mongodb-memory-server handles timeseries collections compared to a standard MongoDB installation.

## Code Example

```ts
// Model definition
const postSchema: Schema = new mongoose.Schema(
  {
    date: {
      type: Date,
      required: true
    },
    content: {
      type: String,
      required: true
    }
  },
  {
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
    timeseries: {
      timeField: "date",
      granularity: "hours"
    },
    autoCreate: true,
    timestamps: true
  }
);

export const Post = mongoose.model<PostDocument>("Post", postSchema);

// Test setup
const { MongoMemoryReplSet } = require("mongodb-memory-server");

const MONGO_VERSION = "8.0.3";

module.exports = async () => {
  const replicaSet = await MongoMemoryReplSet.create({
    instanceOpts: [
      {
        port: parseInt(process.env.DATABASE_IN_MEMORY_PORT)
      }
    ],
    binary: {
      version: MONGO_VERSION
    },
    replSet: { count: 1, storageEngine: "wiredTiger" }
  });
};

// Test that fails
describe("createAllPosts", () => {
  beforeAll(async () => {
    await buildPost({
      content: "test content",
    });
  });

  it("should work with timeseries collection", async () => {
    const posts = await Post.find();
    expect(posts.length).toBe(1);
  });
});

// helpers
async function buildPost(
  overrides: Partial<PostDTOInterface> = {}
): Promise<PostDocument> {
  const data: PostDTOInterface = {
    date: new Date(Date.now()),
    content: faker.lorem.sentence(),
    ...overrides
  };

  return new Post(data).save();
}
```

### Error output
```
MongoServerError: Namespace PostCronService.posts is a view, not a collection
    at InsertOneOperation.execute (node_modules/mongodb/src/operations/insert.ts:82:13)
    at tryOperation (node_modules/mongodb/src/operations/execute_operation.ts:271:14)
    at executeOperation (node_modules/mongodb/src/operations/execute_operation.ts:109:12)
    at Collection.insertOne (node_modules/mongodb/src/collection.ts:277:12)
```

## Do you know *why* it happens?

The issue seems specific to mongodb-memory-server as:
- The exact same code works correctly with a local MongoDB instance
- MongoDB 8.0.3 fully supports timeseries collections

**Comment by hasezoey** [comment]
> When using mongodb-memory-server with a timeseries collection in test environment, attempting to insert documents results in MongoServerError: Namespace X is a view, not a collection

That sounds like a weird error.

> This appears to be a discrepancy in how mongodb-memory-server handles timeseries collections compared to a standard MongoDB installation.

mongodb-memory-server is basically a local installation, as MMS literally only handles download & running `mongod` binaries, so there shouldnt be a discrepancy with the same options.

---

In what part of the provided code does the error occur?
What version were you using when testing a "local installation"?
